apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: senate
  template:
    metadata:
      labels:
        app: senate
      annotations:
        "helm.sh/hook": pre-install
        "helm.sh/hook-weight": "-10"
    spec:
      serviceAccountName: {{ .Release.Name }}-service-account
      containers:
        - name: senate
          image: {{ .Values.image.repository }}
          # command: ["sleep", "3600"]  
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POSTGRES_HOST
              value: "postgres-postgres.{{ .Values.postgres.namespace }}.svc.cluster.local"
            - name: POSTGRES_PORT
              value: "{{ .Values.postgres.port }}"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 80
